name: Update File Tree

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # This will run the workflow every day at midnight

jobs:
  update-filetree:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run update file tree script
      run: |
        chmod +x update_filetree.bat
        ./update_filetree.bat

    - name: Update FILETREE.md
      run: |
        tree -H . -L 2 --noreport --dirsfirst > FILETREE.md

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add FILETREE.md
        git commit -m 'Update file tree'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
