name: Build Docs

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run build_docs.py
      env:
        MARKDOWN_FOLDER: 'src/samples/sample_resumes'
        JSON_FOLDER: 'src/samples/sample_jsons'
        OUTPUT_FOLDER: 'src/samples/output'
      run: python src/build_docs.py

    - name: Archive docx files
      run: |
        cd src/samples/output
        zip -r ../../../../docx_files.zip docx

    - name: Archive pdf files
      run: |
        cd src/samples/output
        zip -r ../../../../pdf_files.zip pdf

    - name: Upload docx files
      uses: actions/upload-artifact@v2
      with:
        name: docx-files
        path: docx_files.zip

    - name: Upload pdf files
      uses: actions/upload-artifact@v2
      with:
        name: pdf-files
        path: pdf_files.zip
