name: Build Docs

on:
  push:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run document formatter
      run: |
        python src/main.py --input-path tests/samples/sample_resumes/md_test_9.md --config-path tests/samples/sample_jsons/taleo.json --output-path tests/samples/output

    - name: Commit and push output
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add tests/samples/output/*
        git commit -m 'Add formatted resume outputs'
        git push
