name: Build Docs

on:
  push:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Process all Markdown and JSON samples
      run: |
        mkdir -p output
        for json_file in tests/samples/sample_jsons/*.json; do
          for md_file in tests/samples/sample_resumes/*.md; do
            python src/main.py --input-json "$json_file" --input-md "$md_file" --output "output"
          done
        done

    - name: Upload formatted documents
      uses: actions/upload-artifact@v2
      with:
        name: formatted-documents
        path: output/
