name: Build Docs

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run build_docs.py
      env:
        MARKDOWN_FOLDER: 'src/samples/sample_resumes'
        JSON_FOLDER: 'src/samples/sample_jsons'
        OUTPUT_FOLDER: 'src/samples/output'
      run: python src/build_docs.py

    - name: Archive docx files
      run: |
        cd src/samples/output
        zip -r docx_files.zip docx

    - name: Archive pdf files
      run: |
        cd src/samples/output
        zip -r pdf_files.zip pdf

    - name: Upload docx artifact
      uses: actions/upload-artifact@v2
      with:
        name: docx-files
        path: src/samples/output/docx_files.zip

    - name: Upload pdf artifact
      uses: actions/upload-artifact@v2
      with:
        name: pdf-files
        path: src/samples/output/pdf_files.zip

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_PAT }}
      with:
        tag_name: 'v1.0.0'
        release_name: 'DOCX and PDF files release'
        draft: false
        prerelease: true

    - name: Upload Release Asset - DOCX files
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_PAT }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: src/samples/output/docx_files.zip
        asset_name: docx_files.zip
        asset_content_type: application/zip

    - name: Upload Release Asset - PDF files
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_PAT }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: src/samples/output/pdf_files.zip
        asset_name: pdf_files.zip
        asset_content_type: application/zip
