name: Build Documentation

on:
  push:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Find and process all JSON and Markdown combinations
      run: |
        for json_file in tests/samples/sample_jsons/*.json; do
          for md_file in tests/samples/sample_resumes/*.md; do
            python src/main.py --ci "$json_file" "$md_file"
          done
        done

    - name: Upload output DOCX and PDF files
      uses: actions/upload-artifact@v2
      with:
        name: formatted-documents
        path: output/docx/**, output/pdf/**
