name: Document Formatter Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format_documents:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: List files for debugging
        run: |
          ls -R

      - name: Run document formatter
        env:
          JSON_FILES: $(ls -t sample_jsons/*.json | head -n 1)
          MARKDOWN_FILES: $(ls -t sample_resumes/*.md | head -n 1)
        run: python markdown_to_formatted_docx.py --ci $JSON_FILES $MARKDOWN_FILES

      - name: Upload output DOCX files
        uses: actions/upload-artifact@v2
        with:
          name: docx-files
          path: output/docx/

      - name: Upload output PDF files
        uses: actions/upload-artifact@v2
        with:
          name: pdf-files
          path: output/pdf/
