name: Document Formatter Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m spacy download en_core_web_sm

    - name: Run document formatter
      env:
        JSON_FILES: './format_json_example.json,./json_test_2.json,./json_test_3.json,./json_test_4.json,./json_test_5.json'
        MARKDOWN_FILES: './resume_md_example.md,./resume_md_example_2.md,./md_test_3.md,./md_test_4.md'
      run: |
        python markdown_to_formatted_docx.py --ci $JSON_FILES $MARKDOWN_FILES

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: formatted-documents
        path: output/
