name: Document Formatter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Find most recent JSON and Markdown files
      id: find-files
      run: |
        echo "JSON_FILES=$(ls sample_jsons/*.json | tail -n 1)" >> $GITHUB_ENV
        echo "MARKDOWN_FILES=$(ls sample_resumes/*.md | tail -n 1)" >> $GITHUB_ENV

    - name: Run document formatter
      run: python markdown_to_formatted_docx.py --ci ${{ env.JSON_FILES }} ${{ env.MARKDOWN_FILES }}

    - name: Upload DOCX artifacts
      uses: actions/upload-artifact@v2
      with:
        name: docx-files
        path: output/docx/

    - name: Upload PDF artifacts
      uses: actions/upload-artifact@v2
      with:
        name: pdf-files
        path: output/pdf/
