name: Document Formatter

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install .

    - name: Run Document Formatter
      env:
        JSON_FILES: $(ls -1t sample_jsons/*.json | head -n 1)
        MARKDOWN_FILES: $(ls -1t sample_resumes/*.md | head -n 1)
      run: |
        python src/markdown_to_formatted_docx.py --ci $JSON_FILES $MARKDOWN_FILES

    - name: Archive Output
      uses: actions/upload-artifact@v2
      with:
        name: formatted-docs
        path: |
          output/docx/*.docx
          output/pdf/*.pdf
