name: Run document formatter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Find most recent files
      id: find_files
      run: |
        echo "JSON_FILES=$(ls -t /mnt/c/Users/Ethan/Documents/user_data/samples/sample_jsons/*.json | head -n 1)" >> $GITHUB_ENV
        echo "MARKDOWN_FILES=$(ls -t /mnt/c/Users/Ethan/Documents/user_data/samples/sample_resumes/*.md | head -n 1)" >> $GITHUB_ENV

    - name: Run document formatter
      run: python markdown_to_formatted_docx.py --ci ${{ env.JSON_FILES }} ${{ env.MARKDOWN_FILES }}

    - name: Upload output DOCX files
      uses: actions/upload-artifact@v2
      with:
        name: output-docx-files
        path: /mnt/c/Users/Ethan/Documents/user_data/samples/output/docx/

    - name: Upload output PDF files
      uses: actions/upload-artifact@v2
      with:
        name: output-pdf-files
        path: /mnt/c/Users/Ethan/Documents/user_data/samples/output/pdf/