name: Generate Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx pylint

    - name: Generate Sphinx documentation
      run: |
        sphinx-apidoc -o docs/source src/
        make -C docs html

    - name: Generate UML diagrams
      run: |
        pyreverse -o png -p project_name src/
        mv classes_project_name.png docs/source/_static/
        mv packages_project_name.png docs/source/_static/

    - name: Upload documentation
      uses: actions/upload-artifact@v2
      with:
        name: documentation
        path: docs/build/html

    - name: Upload UML diagrams
      uses: actions/upload-artifact@v2
      with:
        name: uml-diagrams
        path: docs/source/_static
