name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Initialize Tests
      run: |
        touch tests/__init__.py
        find tests -type d -exec touch {}/__init__.py \;

    - name: Run tests
      run: |
        pytest --junitxml=reports/test-results.xml --cov=src --cov-report=xml:reports/coverage.xml --cov-report=html:reports/coverage

    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: reports/test-results.xml

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: reports/coverage
