name: Run Tests

on: [push, pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ensure __init__.py initialization
      run: |
        touch tests/__init__.py

    - name: Run tests
      run: |
        pytest tests --junitxml=report.xml --tb=short

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: report.xml

    - name: Annotate test results
      if: failure()
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          python:
            - 'tests/**/*.py'
      
    - name: Print test results summary
      if: always()
      run: |
        if [ -f report.xml ]; then
          pip install junit2html
          junit2html report.xml report.html
          echo "## Test Results Summary" >> $GITHUB_STEP_SUMMARY
          cat report.html >> $GITHUB_STEP_SUMMARY
        fi
