name: Tests

on: [push, pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests using unittest
      - name: Run tests
        run: |
          python -m unittest discover -s tests -p "test_*.py"

      # Step 5: Generate coverage report
      - name: Generate coverage report
        run: |
          pip install coverage
          coverage run -m unittest discover -s tests -p "test_*.py"
          coverage report -m
          coverage xml

      # Step 6: Upload coverage to Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage.xml