name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/common-steps.yml
    with:
      python-version: '3.10'
      requirements-file: 'requirements.txt'
    steps:
    - name: Install pytest
      run: pip install pytest
    - name: Run tests
      run: |
        pytest --maxfail=5 --disable-warnings -v tests/