name: Generate Visualizations

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate Plotly Diagram
      run: python scripts/generate_plotly_diagram.py

    - name: Generate Filetree Diagram
      run: python scripts/generate_filetree_diagram.py

    - name: Generate NetworkX Diagram
      run: python scripts/generate_networkx_diagram.py

    - name: Generate Matplotlib Diagram
      run: python scripts/generate_matplotlib_diagram.py

    - name: Upload visualizations
      uses: actions/upload-artifact@v2
      with:
        name: visualizations
        path: docs/visualizations/
